medicalcard/authentication/urls.py
from django.urls import path
from .views import *


app_name = 'authentication'
urlpatterns = [
    path("login/", LoginCustomView.as_view(), name='login'),
    path("logout/", LogoutCustomView.as_view(), name='logout' ),
    path('password_change/', PasswordChangeCustomView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneCustomView.as_view(), name='password_change_done'),
    path('password_reset/',PasswordResetCustomView.as_view(), name='password_reset'),
    path('password_reset/done/',PasswordResetDoneCustomView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmCustomView.as_view(), name='password_reset_confirm'),
    path('reset/done/',PasswordResetCompleteCustomView.as_view(), name='password_reset_complete')
]



medicalcard/medicalcard/urls.py
"""medicalcard URL Configuration

The `urlpatterns` list routes URLs to views.py. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views.py
    1. Add an import:  from my_app import views.py
    2. Add a URL to urlpatterns:  path('', views.py.home, name='home')
Class-based views.py
    1. Add an import:  from other_app.views.py import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from send_mail import views

urlpatterns = [

    path('registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
    path('mail/', views.send_mail_to),
    path('authentication/', include('authentication.urls')),
    # path('my-pacients/', include('pacients.urls')),
    path('visits/', include('visits.urls')),
    path('', include('medcard.urls'))
]

medicalcard/visits/urls.py
from django.urls import path
from . import views

app_name = 'visits'
urlpatterns = [
    path('my-visits/', views.my_visits, name='my_visits'),
    path('add/', views.add_visit, name='add_visit'),
    path('visit/<int:pk>', views.get_visit, name='visit'),
    path('visit/edit/<int:pk>', views.edit_visit, name='edit_visit')
]

medicalcard/authentication/models.py
from django.db import models

class Role(models.Model):
    role = models.CharField(max_length=30)
    description = models.CharField(max_length=30)

    def __str__(self):
        return self.description

medicalcard/authentication/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model

UserModel = get_user_model()


class AuthenticationCustomForm(AuthenticationForm):

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request=None, *args, **kwargs)

medicalcard/authentication/views.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView, \
    PasswordChangeDoneView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

from authentication.forms import AuthenticationCustomForm


class LoginCustomView(LoginView):
    template_name = 'authentication/login.html'
    form_class = AuthenticationCustomForm
    redirect_authenticated_user = True


class LogoutCustomView(LogoutView):
    template_name = 'authentication/login.html'
    form_class = AuthenticationCustomForm

class PasswordChangeCustomView(PasswordChangeView):
    template_name = 'authentication/password_change_form.html'

class PasswordChangeDoneCustomView(PasswordChangeDoneView):
    template_name = 'authentication/password_change_done.html'

class PasswordResetCustomView(PasswordResetView):
    template_name = 'authentication/password_reset_form.html'
    email_template_name = 'authentication/password_reset_email.html'
    success_url = reverse_lazy('authentication:password_reset_done')

class PasswordResetDoneCustomView(PasswordResetDoneView):
    template_name = 'authentication/password_reset_done.html'


class PasswordResetConfirmCustomView(PasswordResetConfirmView):
    template_name = 'authentication/password_reset_confirm.html'

class PasswordResetCompleteCustomView(PasswordResetCompleteView):
    template_name = 'authentication/password_reset_complete.html'

medicalcard/templates/authentication/index.html
{% extends 'base.html' %}
{% block title %}Стартовая страница MedCard{% endblock title %}
{% block content %}
<h2>Доступные функции</h2>
<a href="admin/">Admin</a>
    <a href="{% url 'registration.index'%}">Registration</a>
    <a href="{%url 'medcart.index'%}">Откроется после проверки пароля</a>
<p>Hello. In this page authentication</p>
    <p> Нужен фон с врачами, и табличка логин, пароль.
        Проверка пароля, в случае не пустого заполнения, </br>и
        отсутствия перебросить на регистрацию.
        Ниже описание:
        Medcard - элетронная медицинская карта пациента,</br>
        позволяет просматривать медицинскую историю и тд тп.
    </p>
<div>
    <form action="" method="post" id="authentication">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
    </form>

    <label for="role">Choose role:</label>
    <select id="role" name="role" form="authentication">
    {% for item in list_role %}
    <option value="{{item.role}}">{{item.description}}</option>
    {% endfor %}
    </select>
</div>
    {% autoescape off %}
       {{ context }}
    {% endautoescape %}

{% endblock content %}

medicalcard/templates/authentication/login.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

<div class="container">
    <div class="login-form-wrapper">
        <h1>Log-in</h1>
        {% if form.errors %}
            <p>Your username and password didn't match.Please try again.</p>
        {% else %}
            <p>Please, use the following form to log-in:</p>
        {% endif %}

        <div class="login-form">
            <form action="{% url 'authentication:login' %}" method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ next }}" />
                <p><input type="submit" value="Log-in" class="btn btn-primary"></p>
            </form>
            <p><a href="{% url 'authentication:password_reset' %}">Forgotten your password?</a></p>
        </div>
    </div>
</div>

{% endblock %}

medicalcard/templates/authentication/password_change_done.html
{% extends "base.html" %}
{% block title %}Password changed{% endblock %}
{% block content %}
<h1>Password changed</h1>
<p>Your password has been successfully changed.</p>
{% endblock %}

medicalcard/templates/authentication/password_change_form.html
{% extends "base.html" %}
{% block title %}Change you password{% endblock %}
{% block content %}
<h1>Change you password</h1>
<p>Use the form below to change your password.</p>
<form action="." method="post">
{{ form.as_p }}
<p><input type="submit" value="Change"></p>
{% csrf_token %}
</form>
{% endblock %}

medicalcard/templates/authentication/password_reset_ email.html
Someone asked for password reset for email {{ email }}. Follow the link
below:
{{ protocol }}://{{ domain }}{% url "authentication:password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

medicalcard/templates/authentication/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset{% endblock %}
{% block content %}
<h1>Password set</h1>
<p>Your password has been set. You can
<a href="{% url "authentication:login" %}">log in now</a></p>
{% endblock %}

medicalcard/templates/authentication/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
<p>Please enter your new password twice:</p>
<form action="." method="post">
{{ form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Change my password" /></p>
</form>
{% else %}
<p>The password reset link was invalid, possibly because it
has already been used. Please request a new password reset.</p>
{% endif %}
{% endblock %}

medicalcard/templates/authentication/password_reset_done.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Reset your password</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've
entered the address you registered with.</p>
{% endblock %}

medicalcard/templates/authentication/password_reset_form.html
{% extends "base.html" %}
{% block title %}Reset your password{% endblock %}
{% block content %}
<h1>Forgotten your password?</h1>
<p>Enter your e-mail address to obtain a new password.</p>
<form action="." method="post">
{{ form.as_p }}
<p><input type="submit" value="Send e-mail"></p>
{% csrf_token %}
</form>
{% endblock %}