medicalcard/authentication/urls.py
from django.urls import path
from .views import *


app_name = 'authentication'
urlpatterns = [
    path("login/", LoginCustomView.as_view(), name='login'),
    path("logout/", LogoutCustomView.as_view(), name='logout' ),
    path('password_change/', PasswordChangeCustomView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneCustomView.as_view(), name='password_change_done'),
    path('password_reset/',PasswordResetCustomView.as_view(), name='password_reset'),
    path('password_reset/done/',PasswordResetDoneCustomView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',PasswordResetConfirmCustomView.as_view(), name='password_reset_confirm'),
    path('reset/done/',PasswordResetCompleteCustomView.as_view(), name='password_reset_complete')
]



medicalcard/medcard/urls.py
from django.urls import path

from . import views

app_name = 'medcard'

urlpatterns = [

    path('medcard/patient/', views.patient, name='patient'),
    path('medcard/doctor/', views.doctor, name='doctor'),
    path('medcard/doctor/edit', views.doctor_edit, name="doctor-edit"),
    path('medcard/', views.medcard, name='medcard'),
    # path('analysis/', views.py.Analysis.as_view(), name='analysis_detail'),
    path('analysis/<int:pk>', views.AnalysisDetailView.as_view(), name='analysis_detail'),
    path('disease/<int:pk>', views.DiseaseDetailView.as_view(), name='disease_detail'),
    path('', views.index, name='index'),

]

medicalcard/medicalcard/urls.py
"""medicalcard URL Configuration

The `urlpatterns` list routes URLs to views.py. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views.py
    1. Add an import:  from my_app import views.py
    2. Add a URL to urlpatterns:  path('', views.py.home, name='home')
Class-based views.py
    1. Add an import:  from other_app.views.py import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from send_mail import views

urlpatterns = [

    path('registration/', include('registration.urls')),
    path('admin/', admin.site.urls),
    path('mail/', views.send_mail_to),
    path('authentication/', include('authentication.urls')),
    # path('my-pacients/', include('pacients.urls')),
    path('visits/', include('visits.urls')),
    path('', include('medcard.urls'))
]

medicalcard/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
   ]

medicalcard/visits/urls.py
from django.urls import path
from . import views

app_name = 'visits'
urlpatterns = [
    path('my-visits/', views.my_visits, name='my_visits'),
    path('add/', views.add_visit, name='add_visit'),
    path('visit/<int:pk>', views.get_visit, name='visit'),
    path('visit/edit/<int:pk>', views.edit_visit, name='edit_visit')
]

medicalcard/medcard/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class UserAccount(AbstractUser):
    mob_tel = models.CharField(max_length=20, unique=True)
    patronymick = models.CharField(max_length=20)
    GENDER_CHOICES = [('male', 'Male'), ('female', 'Female')]
    sex = models.CharField(choices=GENDER_CHOICES, max_length=6)
    date_of_birth = models.DateField(null=True)
    city = models.CharField(max_length=20, null=True)
    USERNAME_FIELD = 'mob_tel'

    def get_id_patient(self):
        item = UserAccount.objects.get(pk=self.pk)
        return str(item.patient.pk)

    def get_id_doctor(self):
        item = UserAccount.objects.get(pk=self.pk)
        return str(item.doctor.pk)


class Doctor(models.Model):
    user_account = models.OneToOneField(UserAccount, on_delete=models.CASCADE, null=True)
    description = models.JSONField(default=dict)

    def __str__(self):
        return f"Dr. {self.user_account}"


class Patient(models.Model):
    user_account = models.OneToOneField(UserAccount, on_delete=models.CASCADE, null=True)
    job = models.CharField(max_length=20)
    medical_insurance = models.BooleanField()

    def __str__(self):
        try:
            first_name = self.user_account.first_name
            last_name = self.user_account.last_name
        except AttributeError:
            return str(self.id)
        else:
            return f"{first_name} {last_name}"


class Visit(models.Model):
    date_time = models.DateTimeField()
    doctor = models.ForeignKey(Doctor, on_delete=models.DO_NOTHING, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.DO_NOTHING, null=True)
    result = models.JSONField(default=dict, null=True)


class Analysis(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.DO_NOTHING, null=True)
    date = models.DateField(default=timezone.now)
    result = models.JSONField(default=dict)

    def __str__(self):
        return f"( {self.patient} : {self.date} )"

class Diagnosis(models.Model):
    name = models.CharField(max_length=50)
    description = models.JSONField(default=dict)

    def __str__(self):
        return self.name


class Disease(models.Model):
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(blank=True, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.DO_NOTHING, null=True)
    diagnosis = models.ForeignKey(Diagnosis, on_delete=models.DO_NOTHING, null=True)
    description = models.JSONField(default=dict)

    def __str__(self):
        return f"( {self.patient} : {self.diagnosis} )"

medicalcard/medcard/forms.py
from django import forms


class EditDoctor(forms.Form):
    patronymick = forms.CharField(label='Patronymic', widget=forms.TextInput(attrs={'class': 'form-control'}))
    city = forms.CharField(label='City', widget=forms.TextInput(attrs={'class': 'form-control'}))

medicalcard/medcard/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.utils import timezone as tz
from django.views.generic import DetailView, ListView

from authentication.permissions import is_patient, is_doctor
from django.shortcuts import redirect, render, get_object_or_404
from .models import UserAccount, Analysis, Visit, Disease

from medcard.models import Patient
from .tools.tools import get_random_analysis
from django.contrib import messages

from .forms import EditDoctor


def index(request, message=None):
    context = {'message': message}
    return render(request, template_name="medcard/index.html", context=context)


@login_required
def medcard(request):
    if is_patient(request):
        return redirect('medcard:patient')

    if is_doctor(request):
        return redirect('medcard:doctor')

    raise ValueError("You not doctor or patient, you Harry Houdini")


@login_required
def patient(request):
    response = '''
  I am pacient! But there is error
    '''
    context = {}
    if not is_patient(request):
        return HttpResponse(response)

    patient_id = request.user.patient.id
    patient = get_object_or_404(Patient, id=patient_id)

    today = tz.localtime(tz.now()).date()
    context['today'] = today
    context['patient'] = patient
    context['analysis'] = Analysis.objects.filter(patient=patient).order_by('-date')
    context['disease'] = Disease.objects.filter(patient=patient).order_by('-start_date')

    return render(request, 'medcard/patient_main.html', context=context)


@login_required
def doctor(request):
    user_id = request.user.id
    user_info = UserAccount.objects.filter(id=user_id)

    return render(request, 'medcard/doctor.html', {'user_info': user_info})


def doctor_edit(request):
    user_id = request.user.id
    user = UserAccount.objects.get(id=user_id)
    form = EditDoctor(initial={'patronymick': user.patronymick, 'city': user.city})
    edited = False

    if request.method == "POST":
        user.city = request.POST.get('city')
        user.patronymick = request.POST.get('patronymick')

        user.save()
        edited = True

        form = EditDoctor(initial={'patronymick': user.patronymick, 'city': user.city})

    return render(request, 'medcard/doctor-edit.html', {'form': form, 'edited': edited})


@login_required
def make_analysis(request):
    analysis = ""
    result = get_random_analysis(name=name, laboratory=laboratory)
    try:
        patient = request.GET.get('patient_id')
    except ValueError:
        messages.error("Need to input patient!")

    try:
        analysis = Analysis.objects.create(patient == patient, result=result)
    except Analysis.DoesNotExist:
        messages.error("")
    context = {}
    context['analysis'] = analysis
    return render(request, '', context=context)


def analysis(request):
    context = {}
    try:
        analysis = Analysis.objects.get(id=1)
    except Analysis.DoesNotExist:
        pass
    else:
        context['analysis'] = analysis
    return render(request, 'medcard/analysis.html', context=context)


class AnalysisDetailView(DetailView):
    model = Analysis
    template_name = 'medcard/analysis.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super(AnalysisDetailView, self).get_queryset()
        patient_list = []
        try:
            patient_list.append(self.request.user.patient)
        except AttributeError:
            pass
            # user don`t patient
        try:
            visit_all = Visit.objects.filter(doctor=self.request.user.doctor).distinct()
            patient_doctor_list = [visit.patient for visit in visit_all]
            patient_list += patient_doctor_list
        except AttributeError:
            pass
            # user dont doctor

        return queryset.filter(patient__in=patient_list)


class DiseaseDetailView(DetailView):
    model = Disease
    template_name = 'medcard/disease.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super(DiseaseDetailView, self).get_queryset()
        patient_list = []
        try:
            patient_list.append(self.request.user.patient)
        except AttributeError:
            pass
            # user don`t patient
        try:
            visit_all = Visit.objects.filter(doctor=self.request.user.doctor).distinct()
            patient_doctor_list = [visit.patient for visit in visit_all]
            patient_list += patient_doctor_list
        except  AttributeError:
            pass
            # user dont doctor

        return queryset.filter(patient__in=patient_list)


class Visit(ListView):
    pass
    # add list

medicalcard/templates/medcard/analysis.html
<h1>{{ analysis.result.name }}</h1>
<p>Link id:{{ analysis.id }} </p>
<p>Patient:{{ analysis.patient }}</p>
<p>Laboratory: {{ analysis.result.laboratory }}</p>
<p>Date: {{ analysis.date }}</p>

{%   for key, value in analysis.result.items  %}
        <ul>
        {% if key  != "name" and key != "laboratory" %}
       <li>{{ key }} : {{ value }}</li>
        {%  endif %}
        </ul>


{%  endfor %}

medicalcard/templates/medcard/disease.html
<h1>{{ disease.diagnosis }}</h1>
<p>Link id:{{ disease.id }} </p>
<p>Patient:{{ disease.patient }}</p>
<p>Laboratory: {{ analysis.result.laboratory }}</p>
<p>Start at: {{ disease.start_date }}</p>
<p>End at: {{ disease.end_date }}</p>
{%   for key, value in disease.description.items  %}
        <ul>
       <li>{{ key }} : {{ value }}</li>
        </ul>
{%  endfor %}

medicalcard/templates/medcard/doctor-edit.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %}Editing a profile{% endblock title %}
{% block content %}
<div class="container">
    <h2>Editing a profile</h2>
    {% if edited %}
        <div class="alert alert-success" role="alert">
          Profile is edited
        </div>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="btn-wrapper">
            <input type="submit" value="Edit" class="btn btn-primary">
            <a href="/medcard/doctor" class="btn btn-danger">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

medicalcard/templates/medcard/doctor.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block title %}My profile{% endblock title %}
{% block content %}
    {% if user_info %}
        <div class="profile-container">
            <div class="row">
                <div class="col">
                    <div class="profile-left">
                        {% for user in user_info %}
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png"/>
                            <h5>{{user.first_name}} {{user.last_name}}</h5>
                            <p>{{user.email}}</p>
                            <p>{{user.mob_tel}}</p>
                            <p><i>From {{user.city}}</i></p>
                        {% endfor %}
                    </div>
                </div>
                <div class="col">
                    <ul class="list-group">
                        <li class="list-group-item"><a href="edit">Edit profile</a></li>
                        <li class="list-group-item"><a href="/visits/add/">Add app</a></li>
                        <li class="list-group-item"><a href="/visits/my-visits/">My visits</a></li>
                    </ul>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

medicalcard/templates/medcard/index.html
{% extends 'base.html' %}
{% block title %}Стартовая страница MedCard{% endblock title %}
{% block content %}
<h2>Доступные функции</h2>
<a href="admin/">Admin</a>
    <a href="{% url 'registration:index'%}">Registration</a>
    <a href="{% url 'authentication:login'%}">Log in</a>
    <a href="{% url 'authentication:logout'%}">Log out</a>
    <a href="{%url 'medcard:medcard'%}">Откроется после проверки пароля</a>
<p>Hello. In this page authentication</p>
    <p> Нужен фон с врачами, и табличка логин, пароль.
        Проверка пароля, в случае не пустого заполнения, </br>и
        отсутствия перебросить на регистрацию.
        Ниже описание:
        Medcard - элетронная медицинская карта пациента,</br>
        позволяет просматривать медицинскую историю и тд тп.
    </p>
    {%if flash.error%}
        {%for message in flash.error%}
            <p>{{message}}</p>
        {%endfor%}
    {% endif%}
    {% autoescape off %}
       {{ context }}
    {% endautoescape %}
    {% include "include/messages.html" %}
{% endblock content %}

medicalcard/templates/medcard/patient_main.html
{% extends 'base.html' %}

{% block title %}Стартовая страница пациента MedCard{% endblock title %}
{% block content %}

 {{ today }}<br>
 Patient: {{ patient.user_account.first_name}} {{ patient.user_account.patronymick}} {{ patient.user_account.last_name}}<br>

    История болезней:
    {% if disease %}
        <ul>
            {% for item in disease %}
                <li class="can_be_detailed" value_link="{% url 'medcard:disease_detail' pk=item.id%}">Диагноз:{{ item.diagnosis }}</li>
            {%  endfor %}
        </ul>
    {% else %}
        я абсолютно здоров(а) :)
    {% endif %}
    <br>
      История анализов:
    {% if analysis %}
        <ul>
            {% for item in analysis %}
                <li class="can_be_detailed" value_link="{% url 'medcard:analysis_detail' pk=item.id%}">Дата:{{ item.date}} - {{ item.name }}</li>
            {%  endfor %}
        </ul>
    {% else %}
        я абсолютно здоров(а) :)
    {% endif %}
    <br>
    <br>


    <div class="popup-fade">

	<div class="popup" >
        <a class="popup-close" href="#">Закрыть</a>
            <div  id="popup_detail">
            </div>
	</div>
</div>
    <style>
    .popup {
	position: fixed;
	top: 20%;
	left: 50%;
	padding: 20px;
	width: 360px;
	margin-left: -200px;
	background: #fff;
	border: 1px solid orange;
	border-radius: 4px;
	z-index: 99999;
	opacity: 1;
}
.popup-close {
	position: absolute;
	top: 10px;
	right: 10px;
}
    </style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script>
$(document).ready(function($) {
	// Клик по ссылке "Закрыть".
	$('.popup-close').click(function() {
		$(this).parents('.popup-fade').fadeOut();
		return false;
	});

	// Закрытие по клавише Esc.
	$(document).keydown(function(e) {
		if (e.keyCode === 27) {
			e.stopPropagation();
			$('.popup-fade').fadeOut();
		}
	});

	// Клик по фону, но не по окну.
	$('.popup-fade').click(function(e) {
		if ($(e.target).closest('.popup').length == 0) {
			$(this).fadeOut();
		}
	});
});
$('.can_be_detailed').click(function (){
    value =this.getAttribute("value_link");
    ajax_detail_popup(value);
})
    const popup_detail =  document.querySelector("#popup_detail");
       function ajax_detail_popup(select_value){
                let xhr = new XMLHttpRequest();
                url = select_value;
                xhr.open('GET', url, true);
                xhr.send();
            xhr.onreadystatechange = function() {
                  if (this.readyState != 4){
                      return;
                  }
                  if (this.status != 200) {
                      $('.popup-fade').fadeIn();
                popup_detail.innerHTML = "<p>Детали не доступны</p>";
                        }
                    else{
                    $('.popup-fade').fadeIn();
                popup_detail.innerHTML = this.response;
                  }
            }
       }
$('.popup-fade').fadeOut();

</script>
{% endblock content %}